todo/__init__.py
import os

from flask import Flask


def create_app(test_config=None):
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_mapping(
        SECRET_KEY='dev',
        DATABASE=os.path.join(app.instance_path, 'todo.sqlite'),
    )

    if test_config is None:
        app.config.from_pyfile('config.py', silent=True)
    else:
        app.config.from_mapping(test_config)
    
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass


    from . import db
    db.init_app(app)
    

    from .blueprints import todo
    app.register_blueprint(todo.bp)

    return app

todo/blueprints/todo.py
import functools

from flask import (
    Blueprint, flash, g, redirect, render_template, request, url_for
)

from todo.db import get_db


bp = Blueprint('todo', __name__, url_prefix='/todo')


@bp.route('/', methods=['GET'])
def todo():
    db = get_db()

    items = db.execute(
        "SELECT * FROM todo",
    ).fetchall()

    return render_template('todo.html', items=items)


@bp.route('/create', methods=['POST'])
def create():
    if request.method == 'POST':
        db = get_db()
        content = request.form['content']
        print(content)

        db.execute(
            "INSERT INTO todo (content) VALUES (?)",
            (content,)
        )
        db.commit()

        return redirect(url_for('todo.todo'))
    
    return redirect(url_for('todo.todo'))


@bp.route('/update/<int:id>', methods=['GET', 'POST'])
def update(id):
    db = get_db()

    if request.method == 'POST':
        new_item = request.form['content']
        db.execute(
            "UPDATE todo SET content = ? WHERE id = ?",
            (new_item, id)
        )
        db.commit()
        return redirect(url_for('todo.todo'))

    item = db.execute(
        "SELECT * FROM todo WHERE id = ?",
        (id,)
    ).fetchone()

    return render_template('update_form.html', item=item)


@bp.route('/delete/<int:id>', methods=['GET', 'POST'])
def delete(id):
    db = get_db()

    if request.method == 'POST':
        db.execute(
            "DELETE FROM todo WHERE id = ?",
            (id,)
        )
        db.commit()
        return redirect(url_for('todo.todo'))

    item = db.execute(
        "SELECT * FROM todo WHERE id = ?",
        (id,)
    ).fetchone()

    return render_template('delete_form.html', item=item)

todo/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
</head>
<body>
    
    {% block content %}
        
    {% endblock content %}
        
</body>
</html>

todo/templates/delete_form.html
{% extends "base.html" %}

{% block content %}
<div class="alert alert-danger" role="alert">
    <h4 class="alert-heading">Caution!</h4>
    <p>Are you sure you want to delete this item?</p>
    <hr>
    <p><b>{{ item.content }}</b></p>
    <div class="d-grid gap-2 d-md-flex justify-content-md">
        <form action="{{ url_for('todo.delete', id=item.id) }}" method="post">
            <button type="submit" class="btn btn-danger">Delete</button>
        </form>
    </div>
</div>
{% endblock content %}

todo/templates/todo.html
{% extends 'base.html' %}

{% block title %}Todo List{% endblock title %}


{% block content %}
<section class="vh-100">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col">
                <div class="card" id="list1" style="border-radius: .75rem; background-color: #eff1f2;">
                    <div class="card-body py-4 px-4 px-md-5">

                        <p class="h1 text-center mt-3 mb-4 pb-3 text-primary">
                            <i class="fas fa-check-square me-1"></i>
                            <u>My Todo-s</u>
                        </p>

                        <div class="pb-2">
                            <div class="card">
                                <div class="card-body">
                                    <form action="{{ url_for('todo.create') }}" method="post">
                                        <div class="d-flex flex-row align-items-center">
                                            <input type="text" class="form-control form-control-lg"
                                                id="exampleFormControlInput1" placeholder="Add new..." name="content">
                                            <div>
                                                <button type="submit" class="btn btn-primary" >Add</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>

                        <hr class="my-4">

                        <div class="d-flex justify-content-end align-items-center mb-4 pt-2 pb-3">
                            <p class="small mb-0 me-2 text-muted">Filter</p>
                            <select class="select">
                                <option value="1">All</option>
                                <option value="2">Completed</option>
                                <option value="3">Active</option>
                                <option value="4">Has due date</option>
                            </select>
                            <p class="small mb-0 ms-4 me-2 text-muted">Sort</p>
                            <select class="select">
                                <option value="1">Added date</option>
                                <option value="2">Due date</option>
                            </select>
                            <a href="#!" style="color: #23af89;" data-mdb-toggle="tooltip" title="Ascending"><i
                                    class="fas fa-sort-amount-down-alt ms-2"></i></a>
                        </div>
                            
                        {% for item in items %} 
                        <ul class="list-group list-group-horizontal rounded-0 bg-transparent">                          
                            <li
                                class="list-group-item px-3 py-1 d-flex align-items-center flex-grow-1 border-0 bg-transparent">
                                <p class="lead fw-normal mb-0">{{ item.content }}</p>
                            </li>
                            <li class="list-group-item ps-3 pe-0 py-1 rounded-0 border-0 bg-transparent">
                                <div class="d-flex flex-row justify-content-end mb-1">
                                    <a href="{{ url_for('todo.update', id=item.id) }}" class="text-info" data-mdb-toggle="tooltip" title="Edit todo"><i
                                            class="fas fa-pencil-alt me-3"></i></a>
                                    <a href="{{ url_for('todo.delete', id=item.id) }}" class="text-danger" data-mdb-toggle="tooltip" title="Delete todo"><i
                                            class="fas fa-trash-alt"></i></a>
                                </div>
                                <div class="text-end text-muted">
                                    <a href="#!" class="text-muted" data-mdb-toggle="tooltip" title="Created date">
                                        <p class="small mb-0"><i class="fas fa-info-circle me-2"></i>{{ item.created }}</p>
                                    </a>
                                </div>
                            </li>
                        </ul>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

todo/templates/update_form.html
{% extends "base.html" %}


{% block content %}
<form action="{{ url_for('todo.update', id=item.id) }}" method="post">
    <div class="mb-3">
        <label for="exampleFormControlTextarea1" class="form-label">Edit item</label>
        <input class="form-control" type="text" placeholder="{{ item.content }}" aria-label="default input example" name="content">
    </div>
    <button type="submit" class="btn btn-info">Update</button>
</form>
{% endblock content %}